### ISSUE TITLE
Can we exclude files?

### ISSUE THREAD

**Issue by britztopher** [carsdotcom/gulp-sonar#21]
Just wondering if there is a way to exclude files?  the `sources` property in the options only allows for which files to include.  This can get messy if I have to include all the files since there are only a few i want to exclude.

**Comment by britztopher** [comment]
I tried `sonar.exclusions` within the options, however, report still picks up those files.

**Comment by Hargat** [comment]
@britztopher you can do it, but it different from *source* param. You must specify like that:
`somePath/**`

**Comment by manodupont** [comment]
Can we have a nice solution here ? I would like to exclude a folders, but as wildcards. I mean by this i would like to have excluded, all folders with '__tests__' for instance. How can we do that ?

Thanks

**Comment by machellerogden** [comment]
We are using exclusions with wildcards and have no issues. I'm unable to reproduce.

`exclusions: '**/*.test.js,**/*.spec.js,**/*.driver.js,**/functional-test/**,**/webpack.*,src/index.js',`
