### ISSUE TITLE
Documentation of configuration

### ISSUE THREAD

**Issue by noomidian** [carsdotcom/gulp-sonar#23]
Hello

Can you explain in a tiny doc the aim of each of the configuration options ? I did not understand why we have to configure a jdbc access ? What' s the purpose of this conf ?

Thank you

**Comment by fsmaia** [comment]
Hmm, maybe it could be documented in `README.md` (I can help with that if the author will), but here it goes:

- All the options you send via gulp are converted to a Java properties file (you can check it at node_modules/gulp-sonar/sonar-scanner-2.8/conf/sonar-scanner.properties
- These options are sent to SonarScanner and are available [here](http://docs.sonarqube.org/display/SONAR/Analysis+Parameters)

So, based in these parameters, you have to do the inverse job: convert properties entries to JSON objects.

**Comment by machellerogden** [comment]
Thank you @fsmaia. That is correct.
