### ISSUE TITLE
Prerequisite

### ISSUE THREAD

**Issue by guptaanoop2005** [carsdotcom/gulp-sonar#27]
What are the prerequisites required in order to run it successfully? Do I need sonar runner installed on my system?
I want to run it along with my gulp build to catch JS Sonar violations beforehand.

**Comment by machellerogden** [comment]
The way we use this is just for publishing to SonarQube inside our pipeline. You'll need a SonarQube server running.

https://docs.sonarqube.org/display/SONAR/Installing+the+Server

You can then target that server in the config you provide to gulp-sonar.
