### ISSUE TITLE
Link projectVersion to package.json

### ISSUE THREAD

**Issue by jehon** [carsdotcom/gulp-sonar#4]
projectVersion could be taken out of package.json, wich would be much more simpler when releasing new versions...

See for example: https://www.npmjs.com/package/gulp-tag-version

That would be a nice enhancement...

**Comment by machellerogden** [comment]
Thanks for the suggestion, but I feel like the npm version command takes care of this just fine ... I think a gulp task to do the same thing would be superfluous. I just published out the latest version, by the way. After the last update, I forgot to publish publicly. We had it published on our internal repository but not on npmjs.org. This has been remedied. Sorry for the delay.
